# Generated by Django 2.2.1 on 2019-06-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developpeurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Editeurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plateformes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Jeuxvideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100, null=True)),
                ('date', models.DateTimeField(verbose_name='Date de sortie')),
                ('developpeur', models.ManyToManyField(related_name='jeux_videos', to='jeux_video.Developpeurs')),
                ('editeur', models.ManyToManyField(related_name='jeux_videos', to='jeux_video.Editeurs')),
                ('genre', models.ManyToManyField(related_name='jeux_videos', to='jeux_video.Genres')),
                ('plateforme', models.ManyToManyField(related_name='jeux_videos', to='jeux_video.Plateformes')),
            ],
            options={
                'verbose_name': 'jeux_videos',
                'ordering': ['date'],
            },
        ),
    ]
