# Generated by Django 2.2.1 on 2019-06-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeux_video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developpeurs',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='developpeurs',
            name='nom',
            field=models.CharField(max_length=30, verbose_name="Nom de l'Equipe"),
        ),
        migrations.AlterField(
            model_name='editeurs',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='editeurs',
            name='nom',
            field=models.CharField(max_length=30, verbose_name="Nom de l'Editeur"),
        ),
        migrations.AlterField(
            model_name='genres',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='genres',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom  du Genre'),
        ),
        migrations.AlterField(
            model_name='jeuxvideos',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jeuxvideos',
            name='titre',
            field=models.CharField(max_length=100, verbose_name='Titre du Jeu'),
        ),
        migrations.AlterField(
            model_name='plateformes',
            name='nom',
            field=models.CharField(max_length=30, verbose_name='Nom de la Plateforme'),
        ),
    ]
