# Generated by Django 2.2.1 on 2019-06-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeux_video', '0002_auto_20190607_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='developpeurs',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='editeurs',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genres',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jeuxvideos',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plateformes',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name=1),
            preserve_default=False,
        ),
    ]
